### ISSUE TITLE
what are the proper properties of the objects model used to render pathes

### ISSUE THREAD

**Issue by mustaphakd** [e-oz/angular-d3-map#1]
Right now the map is generating 3 empty g tags with id of "level1".  the path data is not being generated. should the objects format used to render path be in geojson or topojson ?

this  is what each element inside the array returned from getMap() resolve async method looks like:

obj = {
                    id: country.id,
                    type: 'path'  ,
                    objects: temp.coordinates 
                }

temp.coordinates is : [ [[x, y],[x, y],[x, y]], [[x, y],[x, y],[x, y]]]   where x and y are doubles.

**Comment by e-oz** [comment]
Example of data:

```
[  
   {  
      "type":"Feature",
      "properties":{  
         "AREA":29809500,
         "PERIMETER":21822.4,
         "region":"RU-CHU"
      },
      "geometry":{  
         "type":"Polygon",
         "coordinates":[  
            [  
               [  
                  -329.12690955904105,
                  65.75835707089112
               ],
               [  
                  -329.090905959004,
                  65.81936894187223
               ],
               [  
                  -329.05490235896696,
                  65.81123402574141
               ],
               [  
                  -329.090905959004,
                  65.7420872386295
               ],
               [  
                  -329.12690955904105,
                  65.75835707089112
               ]
            ]
         ]
      }
   },
   {  
      "type":"Feature",
      "properties":{  
         "AREA":709138000000,
         "PERIMETER":8196570,
         "region":"RU-CHU"
      },
      "geometry":{  
         "type":"Polygon",
         "coordinates":[  
            [  
               [  
                  -334.16741356422466,
                  66.97045957438245
               ],
               [  
                  -334.16741356422466,
                  66.97045957438245
               ]
            ]
         ]
      }
   },
   {  
      "type":"Feature",
      "properties":{  
         "AREA":12404400,
         "PERIMETER":22845.9,
         "region":"RU-CHU"
      },
      "geometry":{  
         "type":"Polygon",
         "coordinates":[  
            [  
               [  
                  -335.7515719658538,
                  71.41212378180703
               ],
               [  
                  -335.57155396566867,
                  71.36331428502214
               ],
               [  
                  -335.6795647657798,
                  71.37958411728377
               ],
               [  
                  -335.7515719658538,
                  71.41212378180703
               ]
            ]
         ]
      }
   }
]
```

**Comment by e-oz** [comment]
In my code I use it like this: 
topojson.feature(map, map.objects.country).features

**Comment by mustaphakd** [comment]
tnx, 
I finally got a something to show using code similar to ur first post although my polygons are in the wrong winding order; but how can I use : topojson.feature(map, map.objects.country).features (from ur 2nd post) when getMap() function expect a well defined objects type as noted in your documentation.  Wouldn't that last suggestion be a hack?

**Comment by e-oz** [comment]
@mustaphakd little bit more code to help:

```
promise.resolve(
        [{
          type:        'path',
          objects:     topojson.feature(map, map.objects.russia).features
        }]);
```

**Comment by mustaphakd** [comment]
tnx.
didn't think topojson.feature() could take in GEOJSON format. I thought it was limited to TopoJson format only.
by the way your directive has done a great job handling d3 mapping boiler plate code.  
As a side note, I've added zoom behavior in my code to handle manual zooming;  It may be nice to integrate that feature into d3-map.

**Comment by e-oz** [comment]
@mustaphakd it would be great if you'll send pull request with that functional or code in some way - will be glad to add this functional.

**Comment by mustaphakd** [comment]
k,
will do soon as I verify that everythings works just fine!
